name: Love Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_NAME: LOVE-Tetris
  CORE_LOVE_ARTIFACT_NAME: core_tetris
  CORE_LOVE_PACKAGE_PATH: ./core.love
  OUTPUT_FOLDER: ./build

jobs:

  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build core love package
        uses: love-actions/love-actions-core@v1.1.1
        with:
          build-list: ./class/ ./haert/ ./main.lua ./conf.lua ./constants.lua ./classic.lua
          package-path: ${{ env.CORE_LOVE_PACKAGE_PATH }}
      - name: Upload core love package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
          path: ${{ env.CORE_LOVE_PACKAGE_PATH }}

  build-linux:
    runs-on: ubuntu-latest
    needs: [build-core]
    steps:
      - uses: actions/checkout@v4
      - name: Download core love package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
      - name: Build Linux package
        id: build-packages
        uses: love-actions/love-actions-linux@v2
        with:
          app-name: ${{ env.APP_NAME }}
          icon-path: ./.github/build/linux/dev/icon.png
          love-ref: "11.5"
          love-package: ${{ env.CORE_LOVE_PACKAGE_PATH }}
          output-folder: ${{ env.OUTPUT_FOLDER }}
          version-string: "alpha-0.1.0"
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_Linux_AppImage
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.APP_NAME }}.AppImage
