on: [push]
jobs:
  Love-compile:
    runs-on: ubuntu-latest
    steps:
    - name: Love ations bare package
      uses: love-actions/love-actions-core@v1.1.1
      with:
        build-list: ./*.lua ./class ./haert
        package-path: ./bare/tetris.love
        
